# Generated by Django 6.0.4 on 2026-05-10 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FICinema', '0002_alter_usuario_fechanacimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='genero',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro'), ('N', 'Prefiero no decirlo')], default='N', max_length=1),
        ),
    ]
