# Generated by Django 6.0.4 on 2026-05-12 00:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FICinema', '0003_usuario_genero'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.PositiveBigIntegerField(editable=False, unique=True)),
                ('movie_id', models.PositiveBigIntegerField()),
                ('titulo_pelicula', models.CharField(max_length=255)),
                ('fecha', models.DateField()),
                ('hora', models.CharField(max_length=10)),
                ('fechaCompra', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
