# Generated by Django 6.0.4 on 2026-05-12 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FICinema', '0004_entrada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('filas', models.PositiveIntegerField(default=6)),
                ('columnas', models.PositiveIntegerField(default=8)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='entrada',
            name='asiento',
            field=models.CharField(default='A1', max_length=5),
        ),
        migrations.AddField(
            model_name='entrada',
            name='sala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entradas', to='FICinema.sala'),
        ),
        migrations.CreateModel(
            name='SesionCine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.PositiveBigIntegerField()),
                ('titulo_pelicula', models.CharField(max_length=255)),
                ('fecha', models.DateField()),
                ('hora', models.CharField(max_length=10)),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='FICinema.sala')),
            ],
            options={
                'ordering': ['fecha', 'hora', 'sala__nombre'],
            },
        ),
        migrations.AddField(
            model_name='entrada',
            name='sesion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entradas', to='FICinema.sesioncine'),
        ),
        migrations.AddConstraint(
            model_name='entrada',
            constraint=models.UniqueConstraint(fields=('sesion', 'asiento'), name='entrada_asiento_unico_por_sesion'),
        ),
        migrations.AddConstraint(
            model_name='sesioncine',
            constraint=models.UniqueConstraint(fields=('fecha', 'hora', 'sala'), name='sesion_unica_por_fecha_hora_sala'),
        ),
        migrations.AddConstraint(
            model_name='sesioncine',
            constraint=models.UniqueConstraint(fields=('movie_id', 'fecha', 'hora', 'sala'), name='sesion_unica_por_pelicula_fecha_hora_sala'),
        ),
    ]
