# Generated by Django 6.0.4 on 2026-05-12 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FICinema', '0005_sala_entrada_asiento_entrada_sala_sesioncine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesioncine',
            name='duracion_minutos',
            field=models.PositiveIntegerField(default=120),
        ),
    ]
