# Generated by Django 6.0.4 on 2026-05-12 07:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FICinema', '0006_sesioncine_duracion_minutos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entrada',
            options={'ordering': ['-fechaCompra']},
        ),
        migrations.AlterModelOptions(
            name='sala',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='sesioncine',
            options={'ordering': ['fecha', 'inicio', 'sala__id']},
        ),
        migrations.RemoveConstraint(
            model_name='sesioncine',
            name='sesion_unica_por_fecha_hora_sala',
        ),
        migrations.RemoveConstraint(
            model_name='sesioncine',
            name='sesion_unica_por_pelicula_fecha_hora_sala',
        ),
        migrations.AddField(
            model_name='sesioncine',
            name='creada_en',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='sesioncine',
            name='demanda_estimada',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='sesioncine',
            name='fecha_estreno',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sesioncine',
            name='fin',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora real de finalización de la sesión, incluyendo limpieza.', null=True),
        ),
        migrations.AddField(
            model_name='sesioncine',
            name='inicio',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora real de inicio de la sesión.', null=True),
        ),
        migrations.AddField(
            model_name='sesioncine',
            name='margen_limpieza_minutos',
            field=models.PositiveIntegerField(default=20, help_text='Margen de limpieza entre sesiones.'),
        ),
        migrations.AddField(
            model_name='sesioncine',
            name='popularidad',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='sesioncine',
            name='valoracion',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='sesioncine',
            name='duracion_minutos',
            field=models.PositiveIntegerField(default=120, help_text='Duración real de la película en minutos obtenida de TMDB.'),
        ),
        migrations.AlterField(
            model_name='sesioncine',
            name='hora',
            field=models.CharField(blank=True, default='', help_text='Campo auxiliar para mostrar la hora en formato HH:MM.', max_length=10),
        ),
        migrations.AddIndex(
            model_name='sesioncine',
            index=models.Index(fields=['fecha', 'sala'], name='FICinema_se_fecha_c5d073_idx'),
        ),
        migrations.AddIndex(
            model_name='sesioncine',
            index=models.Index(fields=['movie_id', 'fecha'], name='FICinema_se_movie_i_616ce3_idx'),
        ),
        migrations.AddIndex(
            model_name='sesioncine',
            index=models.Index(fields=['inicio', 'fin'], name='FICinema_se_inicio_15d7ae_idx'),
        ),
        migrations.AddConstraint(
            model_name='sesioncine',
            constraint=models.UniqueConstraint(fields=('sala', 'inicio'), name='sesion_unica_por_sala_e_inicio'),
        ),
    ]
