# Generated by Django 6.0.4 on 2026-05-12 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FICinema', '0007_alter_entrada_options_alter_sala_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bono',
            name='usos_restantes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
