# Generated by Django 6.0.4 on 2026-05-13 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FICinema', '0008_bono_usos_restantes'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='bono_usado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entradas_usadas', to='FICinema.bono'),
        ),
        migrations.AddField(
            model_name='entrada',
            name='estado',
            field=models.CharField(choices=[('ACTIVA', 'Activa'), ('USADA', 'Usada'), ('CADUCADA', 'Caducada'), ('CANCELADA', 'Cancelada')], default='ACTIVA', max_length=20),
        ),
    ]
