# Generated by Django 6.0.4 on 2026-05-26 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FICinema', '0011_favorito_sinopsis'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='favorito',
            new_name='FICinema_fa_usuario_57c662_idx',
            old_name='FICinema_fa_usuario_49eafb_idx',
        ),
        migrations.RenameIndex(
            model_name='favorito',
            new_name='FICinema_fa_movie_i_ccad6f_idx',
            old_name='FICinema_fa_movie_i_ebc84b_idx',
        ),
    ]
