# Generated by Django 6.0.4 on 2026-05-31 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FICinema', '0013_sesioncine_generation_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='sesioncine',
            new_name='FICinema_se_sala_id_30dfe8_idx',
            old_name='FICinema_se_sala_i_0f0b7d_idx',
        ),
        migrations.RenameIndex(
            model_name='sesioncine',
            new_name='FICinema_se_movie_i_0bcc77_idx',
            old_name='FICinema_se_movie_i_b3e40c_idx',
        ),
    ]
