# Generated by Django 6.0.4 on 2026-06-03 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FICinema', '0015_resena'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='resena',
            new_name='FICinema_re_movie_i_0ff157_idx',
            old_name='FICinema_re_movie__0b0f6c_idx',
        ),
        migrations.RenameIndex(
            model_name='resena',
            new_name='FICinema_re_usuario_5f2ee7_idx',
            old_name='FICinema_re_usuario_6b80a5_idx',
        ),
        migrations.RenameIndex(
            model_name='resena',
            new_name='FICinema_re_puntuac_734c3a_idx',
            old_name='FICinema_re_puntuac_01e37f_idx',
        ),
    ]
