# Generated by Django 6.0.4 on 2026-06-05 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FICinema', '0017_validacionentrada'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='validacionentrada',
            new_name='FICinema_va_entrada_b62181_idx',
            old_name='FICinema_va_entrada_41bd41_idx',
        ),
        migrations.RenameIndex(
            model_name='validacionentrada',
            new_name='FICinema_va_resulta_c92d20_idx',
            old_name='FICinema_va_resulta_0c6e96_idx',
        ),
        migrations.RenameIndex(
            model_name='validacionentrada',
            new_name='FICinema_va_usuario_8cea19_idx',
            old_name='FICinema_va_usuario_508949_idx',
        ),
    ]
