"""
Django settings for Django project.

Generated by 'django-admin startproject' using Django 6.0.4.
"""

from pathlib import Path
import os
import sys
from dotenv import load_dotenv

try:
    import dj_database_url
except ImportError:
    dj_database_url = None

load_dotenv()

BASE_DIR = Path(__file__).resolve().parent.parent


# =========================
# Helpers
# =========================

def env_bool(nombre, defecto=False):
    return os.getenv(nombre, str(defecto)).strip().lower() in ("1", "true", "yes", "on")


def env_int(nombre, defecto):
    try:
        return int(os.getenv(nombre, str(defecto)))
    except (TypeError, ValueError):
        return defecto


def split_env_list(nombre, valor_por_defecto=""):
    return [
        valor.strip()
        for valor in os.getenv(nombre, valor_por_defecto).split(",")
        if valor.strip()
    ]


USING_TESTS = "test" in sys.argv


# =========================
# Seguridad básica
# =========================

SECRET_KEY = os.getenv("SECRET_KEY", "django-insecure-dev-key")

DEBUG = env_bool("DEBUG", True)

ALLOWED_HOSTS = split_env_list(
    "ALLOWED_HOSTS",
    "localhost,127.0.0.1,0.0.0.0,.ngrok-free.app,.trycloudflare.com,web,ficinema.onrender.com",
)

render_host = os.getenv("RENDER_EXTERNAL_HOSTNAME", "").strip()
if render_host and render_host not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(render_host)

CSRF_TRUSTED_ORIGINS = split_env_list(
    "CSRF_TRUSTED_ORIGINS",
    "https://*.trycloudflare.com,https://*.ngrok-free.app,https://ficinema.onrender.com",
)

if render_host:
    render_origin = f"https://{render_host}"
    if render_origin not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(render_origin)

USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

CSRF_COOKIE_SAMESITE = "Lax"
SESSION_COOKIE_SAMESITE = "Lax"

if not DEBUG:
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SECURE = True


# =========================
# Apps
# =========================

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Necesario para Resend mediante django-anymail.
    # Si no tienes django-anymail instalado, instálalo con:
    # pip install django-anymail
    "anymail",

    "FICinema",
]


MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


ROOT_URLCONF = "Django.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "Django.wsgi.application"


# =========================
# Base de datos
# =========================

DATABASE_URL = os.getenv("DATABASE_URL", "").strip()

if DATABASE_URL:
    if dj_database_url is None:
        raise RuntimeError("DATABASE_URL requiere instalar dj-database-url.")

    DATABASES = {
        "default": dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=600,
            ssl_require=env_bool("DB_SSL_REQUIRE", True),
        )
    }
else:
    SQLITE_PATH = os.getenv("SQLITE_PATH", "").strip()
    sqlite_name = Path(SQLITE_PATH) if SQLITE_PATH else BASE_DIR / "db.sqlite3"

    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": sqlite_name,
        }
    }


# =========================
# Usuario / login
# =========================

AUTH_USER_MODEL = "FICinema.Usuario"

LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "index_peliculas"
LOGOUT_REDIRECT_URL = "index_peliculas"


# =========================
# Validación contraseñas
# =========================

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# =========================
# Idioma / hora
# =========================

LANGUAGE_CODE = "es-es"
TIME_ZONE = "Europe/Madrid"

USE_I18N = True
USE_TZ = True


# =========================
# Static files
# =========================

STATIC_URL = "/static/"

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

STATIC_ROOT = BASE_DIR / "staticfiles"

STATICFILES_BACKEND = (
    "django.contrib.staticfiles.storage.StaticFilesStorage"
    if DEBUG or USING_TESTS
    else "whitenoise.storage.CompressedManifestStaticFilesStorage"
)

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": STATICFILES_BACKEND,
    },
}


# =========================
# APIs externas
# =========================

TMDB_API_KEY = os.getenv("TMDB_API_KEY")
TMDB_ACCESS_TOKEN = os.getenv("TMDB_ACCESS_TOKEN")
OMDB_API_KEY = os.getenv("OMDB_API_KEY")
YOUTUBE_API_KEY = os.getenv("YOUTUBE_API_KEY")
GOOGLE_MAPS_API_KEY = os.getenv("GOOGLE_MAPS_API_KEY")

STRIPE_SECRET_KEY = os.getenv("STRIPE_SECRET_KEY")
STRIPE_PUBLISHABLE_KEY = os.getenv("STRIPE_PUBLISHABLE_KEY")

PAYMENT_SIMULATION_MODE = env_bool("PAYMENT_SIMULATION_MODE", True)

PUBLIC_BASE_URL = os.getenv("PUBLIC_BASE_URL", "").strip().rstrip("/")
if not PUBLIC_BASE_URL and render_host:
    PUBLIC_BASE_URL = f"https://{render_host}"


# =========================
# Email
# =========================
# En local se usa la consola por defecto. En producción se puede activar Resend
# con EMAIL_PROVIDER=resend y RESEND_API_KEY. Mientras se use onboarding@resend.dev,
# el envío queda limitado al correo asociado a la cuenta de Resend; para enviar a
# cualquier usuario real es necesario configurar un dominio propio verificado.

EMAIL_PROVIDER = os.getenv("EMAIL_PROVIDER", "").strip().lower()

EMAIL_REQUIRED_FOR_PURCHASE = env_bool("EMAIL_REQUIRED_FOR_PURCHASE", False)
EMAIL_TIMEOUT = env_int("EMAIL_TIMEOUT", 6)
EMAIL_TEST_RECIPIENT_OVERRIDE = os.getenv("EMAIL_TEST_RECIPIENT_OVERRIDE", "").strip()

if USING_TESTS:
    EMAIL_BACKEND = "django.core.mail.backends.locmem.EmailBackend"

elif EMAIL_PROVIDER == "resend":
    EMAIL_BACKEND = os.getenv(
        "EMAIL_BACKEND",
        "anymail.backends.resend.EmailBackend",
    )

elif os.getenv("EMAIL_BACKEND"):
    EMAIL_BACKEND = os.getenv("EMAIL_BACKEND")

else:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"


# Configuración Resend / Anymail
ANYMAIL = {
    "RESEND_API_KEY": os.getenv("RESEND_API_KEY", ""),
}

RESEND_FROM_EMAIL = os.getenv(
    "RESEND_FROM_EMAIL",
    "FICinema <onboarding@resend.dev>",
)

DEFAULT_FROM_EMAIL = os.getenv(
    "DEFAULT_FROM_EMAIL",
    RESEND_FROM_EMAIL if EMAIL_PROVIDER == "resend" else "FICinema <no-reply@ficinema.local>",
)

SERVER_EMAIL = DEFAULT_FROM_EMAIL


# Configuración SMTP clásica.
EMAIL_HOST = os.getenv("EMAIL_HOST", "")
EMAIL_PORT = env_int("EMAIL_PORT", 587)
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
EMAIL_USE_TLS = env_bool("EMAIL_USE_TLS", True)
EMAIL_USE_SSL = env_bool("EMAIL_USE_SSL", False)

# Tiempo máximo de espera para el backend de correo.
